# Generated by Django 3.2.7 on 2021-09-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210921_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='username',
        ),
    ]
